version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/site"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency] "
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency] "